title: Oasis

description: >-
  a jekyll site template for Codrops.
baseurl: "https://ghosts.wormhole.technology"
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
